export const START_SIGNUP = "START_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const START_LOGIN = "START_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const START_RECIPE = "START_RECIPE";
export const RECIPE_POST_SUCCESS = "RECIPE_POST_SUCCESS";
export const RECIPE_POST_FAIL = "RECIPE_POST_FAIL";

export const START_GETTING_RECIPES = "START_GETTING_RECIPES";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_ERROR = "GET_RECIPES_ERROR";

export const START_POST_INGREDIENT = "START_POST_INGREDIENT";
export const POST_INGREDIENT_SUCCESS = "POST_INGREDIENT_SUCCESS";
export const POST_INGREDIENT_FAIL = "POST_INGREDIENT_FAIL";

export const START_UPDATE_RECIPE = "START_UPDATE_RECIPE";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_FAIL = "UPDATE_RECIPE_FAIL";

export const START_DELETE_RECIPE = "START_DELETE_RECIPE";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_FAIL = "DELETE_RECIPE_FAIL";

export const START_EDIT_INGREDIENT = "START_EDIT_INGREDIENT";
export const EDIT_INGREDIENT_SUCCESS = "EDIT_INGREDIENT_SUCCESS";
export const EDIT_INGREDIENT_FAIL = "EDIT_INGREDIENT_FAIL";

export const START_INGREDIENT_DELETE = "START_INGREDIENT_DELETE";
export const DELETE_INGREDIENT_SUCCESS = "DELETE_INGREDIENT_SUCCESS";
export const DELETE_INGREDIENT_FAIL = "DELETE_INGREDIENT_FAIL";

export const START_POST_INSTRUCTION = "START_POST_INSTRUCTION";
export const POST_INSTRUCTION_SUCCESS = "POST_INSTRUCTION_SUCCESS";
export const POST_INSTRUCTION_FAIL = "POST_INSTRUCTION_FAIL";
