export const START_SIGNUP = "START_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const START_LOGIN = "START_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const START_RECIPE = "START_RECIPE";
export const RECIPE_POST_SUCCESS = "RECIPE_POST_SUCCESS";
export const RECIPE_POST_FAIL = "RECIPE_POST_FAIL";

export const START_GETTING_RECIPES = "START_GETTING_RECIPES";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_ERROR = "GET_RECIPES_ERROR";

export const START_POST_INGREDIENT = "START_POST_INGREDIENT";
export const POST_INGREDIENT_SUCCESS = "POST_INGREDIENT_SUCCESS";
export const POST_INGREDIENT_FAIL = "POST_INGREDIENT_FAIL";
